ARG VERSION=latest

FROM maven:$VERSION

COPY files/default-settings.xml /usr/share/maven/conf/settings.xml
COPY bin/mvn-wrapper.sh /usr/bin/mvn-wrapper.sh

RUN chmod +x /usr/bin/mvn-wrapper.sh && \
    chgrp  0 /usr/bin/mvn-wrapper.sh && \
        chmod g=u /usr/bin/mvn-wrapper.sh && \
    chgrp -R 0 /root && \
        chmod -R g=u /root

RUN addgroup -g 1000 -S maven && \
    adduser -u 1000 -S maven -G maven

USER 1000

COPY version /etc/version