FROM alpine/git

WORKDIR /root


RUN wget https://github.com/mikefarah/yq/releases/download/v4.23.1/yq_linux_amd64 -O /usr/bin/yq \
    && chmod +x /usr/bin/yq

RUN  apk add bash \
    && mkdir -m 700 /root/.ssh

COPY bin/git-workflow.sh /usr/bin/
RUN chmod +x /usr/bin/git-workflow.sh

RUN chgrp -R 0 /root && \
        chmod -R g=u /root

COPY version /etc/version

ENTRYPOINT ["/usr/bin/git-workflow.sh"]

CMD ["help"]