FROM postman/newman

RUN npm install -g newman-reporter-htmlextra && \
    npm install -g newman-reporter-json && \
    npm install -g newman-reporter-html \

RUN addgroup -g 1000 -S newman && \
    adduser -u 1000 -S newman -G newman

USER 1000

COPY version /etc/version