FROM argoproj/argocd:latest
# Switch to root for the ability to perform install
USER root

RUN apt-get update && \
    apt-get install -y wget

RUN wget -qO - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz \
        | tar -xzf - -C /usr/local/bin --overwrite && \
    wget -qO - https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz \
        | tar -xzf - -C /usr/local/bin --overwrite --strip-components=1  linux-amd64/helm \
    && wget -qcO - https://github.com/mikefarah/yq/releases/download/v4.23.1/yq_linux_amd64 > /usr/bin/yq \
    && chmod +x /usr/bin/yq

# Switch back to non-root user
USER argocd