FROM ubuntu:jammy

ARG OC_VERSION

RUN apt update -y && apt install -y wget vim bash \
    && wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-$OC_VERSION/openshift-client-linux.tar.gz \
    && tar -xvf openshift-client-linux.tar.gz --directory=/usr/bin/ \
    && rm openshift-client-linux.tar.gz \
    && chmod -R g=u  /usr/bin/ \
    && chmod -R +x  /usr/bin/ \
    && chgrp -R 0 /usr/bin/

RUN addgroup --gid 1000 --system kubectl && \
    adduser kubectl --uid 1000 --ingroup kubectl

COPY version /etc/version

USER 1000

ENTRYPOINT ["bash"]


