FROM alpine

ARG OC_VERSION

RUN apk --no-cache add vim bash \
    && wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-$OC_VERSION/openshift-client-linux.tar.gz \
    && tar -xvf openshift-client-linux.tar.gz --directory=/usr/bin/ \
    && rm openshift-client-linux.tar.gz \
    && chmod g=u +x /usr/bin \
    && chgrp 0 /usr/bin

ENTRYPOINT ["bash"]
CMD ["sleep", "infinity"]


