name: Release Containerimage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.8.6-openjdk-11
          - 3.8.6-openjdk-17
          - 3.8.6-openjdk-8
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: maven
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: maven/Containerfile
          directory: maven
          buildArgs: VERSION=${{ matrix.version }}
          addLatest: true
          tags: ${{ matrix.version }},latest
  build-newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: source-version
        id: source-version
        run: echo "version=$(cat newman/version)" >> $GITHUB_OUTPUT
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: newman
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: newman/Containerfile
          directory: newman
          addLatest: true
          tags: ${{ steps.source-version.outputs.version }},latest
  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - build-maven
      - build-newman
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/74975412?s=200&v=4
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''