name: Release Containerimage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.8.6-openjdk-11
          - 3.6.3-openjdk-11
          - 3.8.2-openjdk-11
          - 3.8.6-openjdk-18
          - 3.8.6-openjdk-8
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: push-container-image
        with:
          image: maven
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: maven/Containerfile
          directory: maven
          buildArgs: VERSION=${{ matrix.version }}
          addLatest: true
          tags: ${{ matrix.version }},latest
  build-buildah:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - v1.29
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: push-container-image
        with:
          image: buildah
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: buildah/Containerfile
          directory: buildah
          buildArgs: VERSION=${{ matrix.version }}
          addLatest: true
          tags: ${{ matrix.version }},latest
  build-kubectl-oc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 4.10
          - 4.11
          - 4.12
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: build-openshift-latest
        with:
          image: kubectl-oc
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: kubectl-oc/Containerfile
          directory: kubectl-oc
          addLatest: true
          tags: ${{ matrix.version }},latest
          buildArgs: OC_VERSION=${{ matrix.version }}
  build-newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: source-version
        id: source-version
        run: echo "version=$(cat newman/version)" >> $GITHUB_OUTPUT
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: push-container-image
        with:
          image: newman
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: newman/Containerfile
          directory: newman
          addLatest: true
          tags: ${{ steps.source-version.outputs.version }},latest
  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - build-maven
      - build-newman
      - build-kubectl-oc
      - build-buildah
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/74975412?s=200&v=4
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''
