name: Release Containerimage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: phish108/autotag-action@1.1.37
        name: tag
        with:
          github-token: ${{ secrets.PAT}}
          with-v: "true"
          release-branch: main
  build-git-workflows:
    runs-on: ubuntu-latest
    needs:
      - create-tag
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: git-workflows
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: git-workflows/Containerfile
          directory:  git-workflows
          addLatest: true
          tags: ${{ steps.checkout.outputs.new-tag }}
  build-maven:
    runs-on: ubuntu-latest
    needs:
      - create-tag
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: maven
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: maven/Containerfile
          directory: maven
          addLatest: true
          tags: ${{ steps.checkout.outputs.new-tag }}
  build-slack-notifications:
    runs-on: ubuntu-latest
    needs:
      - create-tag
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: slack-notify
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: slack-notifications/Containerfile
          directory: slack-notifications
          addLatest: true
          tags: ${{ steps.checkout.outputs.new-tag }}
  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - build-git-workflows
      - build-maven
      - build-slack-notifications
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/74975412?s=200&v=4
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''